### ISSUE TITLE
Final state is inf if save_states=True

### ISSUE THREAD

**Issue by dkweiss31** [dynamiqs/dynamiqs#666]
I am finding that sometimes the final state returned by sesolve in the case where `save_states=True` is sometimes all infs. See the following MWE. I have checked that this bug was not introduced in the most recent update to `pwc` from earlier today, nor from any recent commits. 
```python
import dynamiqs as dq
import jax.numpy as jnp

a = dq.destroy(2)
ntimes = 4
tsave = jnp.linspace(0, 9.0, ntimes)
initial_states = [dq.basis(2, 0), ]
H = dq.pwc(tsave, jnp.ones(ntimes - 1), a + dq.dag(a))

res_save = dq.sesolve(H, initial_states, tsave, options=dq.Options(save_states=True))
res_nosave = dq.sesolve(H, initial_states, tsave, options=dq.Options(save_states=False))
offending_states = res_save.states[:, -1]  # [[[inf+0.j] [inf+0.j]]]
correct_final_states = res_nosave.states  # [[[-0.91112924 + 0.j] [ 0. -0.41211867j]]]
``` 
Strangely enough, if I change the final time from 9.0 to 8.0, the issue disappears and the final states agree.

**Comment by pierreguilmin** [comment]
Good catch! I've started investigating, it's definitely an issue with the `pwc` Hamiltonian format, it works fine if you replace
```diff
- H = dq.pwc(tsave, jnp.ones(ntimes - 1), a + dq.dag(a))
+ H = a + dq.dag(a)
```

The bug was introduced by this commit https://github.com/dynamiqs/dynamiqs/commit/53369323e2de359c5ef631f5751d13b922de05e8.

**Comment by pierreguilmin** [comment]
(I just noticed the issue number 👹)

**Comment by dkweiss31** [comment]
Possibly a related issue that pops up if you want to save states in the case where all times in `tsave` are the same. This occurs even for a constant Hamiltonian (it occurs also for `timecallable`)
```python
import dynamiqs as dq

H = dq.sigmaz()
tsave = [0.0, 0.0]
psi0 = dq.basis(2, 0)
save_false = dq.sesolve(H, psi0, tsave, options=dq.Options(save_states=False))
save_true = dq.sesolve(H, psi0, tsave, options=dq.Options(save_states=True))
print(save_false.states)  # [[1.+0.j] [0.+0.j]]
print(save_true.states)  # [[[inf+0.j] [inf+0.j]] [[inf+0.j] [inf+0.j]]]
``` 
This problem persists for e.g. `tsave = [0.0, 0.0, 0.0]` or `tsave = [1.0, 1.0]` but disappears if we take `tsave = [0.0, 0.0, 1.0]` or even `tsave = [0.0, 0.0, 1.0, 1.0]`. It's possible this is in fact a diffrax issue, which I will try to confirm.

**Comment by yunweilu** [comment]
Met the same problem where save_states=True make final states amplitude go inf

**Comment by pierreguilmin** [comment]
@yunweilu, thanks for the heads-up. Does it also happen when using `dq.pwc` for one of the operators?

**Comment by yunweilu** [comment]
> @yunweilu, thanks for the heads-up. Does it also happen when using `dq.pwc` for one of the operators?

Yes!

To be more precise, here is my code:
```
import dynamiqs as dq
import jax.numpy as jnp
import qontrol as ql

H0 = jnp.array([[0., 0., 0., 0.],
                            [0., 0.58838704, 0., 0.],
                            [0., 0., 0.96262412, 0.],
                            [0., 0., 0., 1.5510177]]) * 2 * jnp.pi

Q1 = jnp.array([[-5.62333713e-34-2.99208307e-17j,  6.78898493e-20+4.01183587e-02j,
                             1.52766012e-22-9.52401756e-03j,  2.01550306e-30+1.64824548e-14j],
                            [ 6.78898493e-20-4.01183587e-02j,  5.23928460e-34-4.61772417e-17j,
                            -2.87703215e-32+1.66231870e-14j,  1.09707785e-18+9.09230727e-03j],
                            [ 1.52766012e-22+9.52401756e-03j, -2.87599643e-32-1.66171241e-14j,
                            -3.41118472e-34-3.04518728e-17j,  4.91668737e-18+4.01794253e-02j],
                            [ 2.01568565e-30-1.64839472e-14j,  1.09707785e-18-9.09230727e-03j,
                             4.91668737e-18-4.01794253e-02j,  7.81952100e-34-4.67082776e-17j]])

Q2 = jnp.array([[-4.50794789e-32-1.04753605e-17j,  1.46605360e-20+8.66339592e-03j,
                            -9.96073221e-22+6.20990147e-02j, -1.28342958e-30-1.05503825e-14j],
                            [ 1.46605360e-20-8.66339592e-03j,  2.89292641e-32-1.00211375e-17j,
                             2.69293651e-32+9.62645619e-15j,  7.48527042e-18+6.20360521e-02j],
                            [-9.96073221e-22-6.20990147e-02j,  2.69336328e-32-9.62129964e-15j,
                            -1.91333418e-32+3.25386604e-18j, -1.09340154e-18-8.93533432e-03j],
                            [-1.28359917e-30+1.05516660e-14j,  7.48527042e-18-6.20360521e-02j,
                            -1.09340154e-18+8.93533432e-03j, -7.96389184e-32+3.70800821e-18j]])

time, dt = 100, 0.1
ntimes = int(time // dt) + 1
tsave = jnp.linspace(0, time, ntimes)
Hc = -0.21594591603445407 * Q1 + Q2
Hcs = [Hc]
initial_states = [dq.basis(4, 0)]
initial_guess = jnp.ones((len(Hcs), ntimes - 1))
init_drive_params = jnp.array([initial_guess])

def H_func(drive_params: list) -> dq.TimeArray:
       H = H0
       for Hc, drive_param in zip(Hcs, drive_params):
              H = dq.pwc(tsave, drive_param, Hc) + H0
       return H

fq_model = ql.sesolve_model(H_func, initial_states, tsave)
result = fq_model(parameters=init_drive_params)
result[0].final_state``
```

**Comment by gautierronan** [comment]
Setting `return None` instead of `return self.times` in https://github.com/dynamiqs/dynamiqs/blob/e28add49c55cfac24c4068fd351f16bc41b0ff90/dynamiqs/time_array.py#L451-L453 indeed seems to fix the bug. My guess is that diffrax tries to make a final step from `t0=discontinuity_ts[-1]` to `t1=tsave[-1]`, and, as per the other bug (https://github.com/patrick-kidger/diffrax/issues/488) because these `t0==t1`, this returns an `inf` state.

It should be fixed with the [PR](https://github.com/patrick-kidger/diffrax/pull/494) of @dkweiss31 to be merged soon. Then we still need to wait for a diffrax release and dynamiqs release. We could temporarely disable the discontinuity times though.

**Comment by pierreguilmin** [comment]
Here's a temporary fix to wait for the proper one, instead of calling `dq.pwc()`, call `pwc_fixed()`:
```python
def pwc_fixed(times, values, array):
    from dynamiqs.time_array import PWCTimeArray

    class PWCTimeArrayTempFix(PWCTimeArray):
        @property
        def discontinuity_ts(self):
            return None

        @property
        def in_axes(self):
            return PWCTimeArrayTempFix(None, 0, None)

    H = dq.pwc(times, values, array)
    return PWCTimeArrayTempFix(H.times, H.values, H.array)
```
For example, for the code block of opening the issue just replace:
```diff
- H = dq.pwc(tsave, jnp.ones(ntimes - 1), a + dq.dag(a))
+ H = pwc_fixed(tsave, jnp.ones(ntimes - 1), a + dq.dag(a))
```

Note that consequently the solver will not _exactly_ step at the discontinuity times of your pwc pulse (this is the reason for this attribute). But if the timing is fine-grained enough it shouldn't make a large difference. And hopefully we can release the fix soon 🤞

**Comment by dkweiss31** [comment]
So my diffrax [PR](https://github.com/patrick-kidger/diffrax/pull/494) has just been merged. Returning to this example, unfortunately the issue persists even when using the version of diffrax with my fix (on the dev branch). It seems the bug is coming from somewhere else. Thank you though @pierreguilmin for the temporary fix!
